name: build status

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - name: Use Node.js
    uses: actions/setup-node@v1
    with:
      node-version: '14.x'
  - name: Install dependencies and build
    run: |
      yarn --frozen-lockfile
      yarn build
  - name: Zip build and release
    run: |
      zip -r build.zip build
      echo "Release"